### ISSUE TITLE
[QUESTION] How does tenancy work? 

### ISSUE THREAD

**Issue by Addyvan** [AccessibleAI/cnvrgio-operator#49]
In the values file I see:
```yaml
tenancy:
  enabled: "false"
  dedicatedNodes: "false"
  cnvrg:
    key: "cnvrg-taint"
    value: "true"
```

I'm assuming this allows us to section off specific nodes to be used by cnvrg using taints and tolerations. Some guidance as to the syntax in play here would be much appreciated.

Let's use the example of a cluster with the followed nodes:
- `gpunode1`*
- `gpunode2`*
- `cpunode1`
- `cpunode2`*

If I want cnvrg deployed on the * nodes:
1. Is tenancy the way to do that
2. If so, how might I go about implementing this?

**Comment by Dimss** [comment]
`tenancy.enabled=true && tenancy.dedicatedNodes=false` meaning `cnvrg control plan` will run on **certain nodes alongs side with other workloads**. This functionality achieved by labelling desired K8S nodes, and applying `node selectors` on all `cnvrg control  plan` workloads. 

For example, 
Command `kubectl label node <node1> <node2> cnvrg-taint=true` will label nodes with `cnvrg-taint=true`.
then, all cnvrg workloads will have `node selector` 
```
      nodeSelector:
        cnvrg-taint: "true"
```

The `tenancy.enabled=true && tenancy.dedicatedNodes=true` will make sure that `cnvrg control plan` running on **dedicated nodes, without any other workloads**.  This functionality achieved by labelling desired K8S nodes + adding tenants on nodes. 

For example:
Commands `kubectl label node <node1> <node2> cnvrg-taint=true` + `kubectl taint node <node1> <node2>  cnvrg-taint=true:NoSchedule` will add labels and taints to nodes, then each cnvrg control plan workload will have both `node selector` and `toleration`
```
      nodeSelector:
        cnvrg-taint: "true"
```
 
```
      tolerations:
      - key: "cnvrg-taint"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
```

Here is an Ansible snippet from the Operator code thats cover tenancy functionality:
```
{%  if tenancy.enabled == "true" %}
      nodeSelector:
        {{ tenancy.cnvrg.key }}: "{{ tenancy.cnvrg.value }}"
{%  endif %}
{%  if tenancy.enabled == "true" and tenancy.dedicated_nodes == "true" %}
      tolerations:
      - key: "{{ tenancy.cnvrg.key }}"
        operator: "Equal"
        value: "{{ tenancy.cnvrg.value }}"
        effect: "NoSchedule"
{% endif %}
