### ISSUE TITLE
[QUESTION] How to configure NFS support declaratively

### ISSUE THREAD

**Issue by Addyvan** [AccessibleAI/cnvrgio-operator#50]
We are currently running an NFS server using the [rook-nfs CRD](https://rook.io/docs/rook/v1.5/nfs-crd.html), which creates the following service for connecting to the NFS from inside the cluster. 
```yaml
kind: Service
metadata:
  name: rook-nfs
  namespace: rook-nfs
  labels:
    app: rook-nfs
spec:
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  - name: rpc
    port: 111
    protocol: TCP
    targetPort: 111
  selector:
    app: rook-nfs
  sessionAffinity: None
  type: ClusterIP
```

Currently, our process is to exec into the cnvrg app pod and run:
```
root@app-646f8bfc-2jv5s:~# rails nfs:create
** Invoke nfs:create (first_time)
** Invoke environment (first_time)
** Execute environment
Raven 2.7.4 ready to catch errors
** Execute nfs:create
Enter the NFS ip:
*******
Enter the NFS host path:
*******
Enter the NFS total space (in TB):
*******
Successfully attached NFS to *******
```

Can these parameters be added to the chart somewhere is that something that isn't yet supported? 

edit: Is there also another step needed to get this to work?
