### ISSUE TITLE
[SUGGESTION] Separate operator and cnvrg-app deployments

### ISSUE THREAD

**Issue by Addyvan** [AccessibleAI/cnvrgio-operator#55]
## Context

We use ArgoCD to update our cluster manifests based off our git repos (gitops). The ideal way of updating cnvrg for us is to:
* PR to staging which will deploy to a staging cluster
* Verify functionality
* PR to master which will deploy to prod

Under the hood, it seems as though we only need to edit cnvrg-app, then the operator will perform the updates automatically for us. 

## Description of the problem

Currently, the deployment of the operator is tied in with the deployment of the cnvrg-app CRD in the [chart](https://github.com/AccessibleAI/cnvrgio-operator/tree/develop/chart). This causes some serious concerns as some of the hooks found in the helm chart can be quite destructive to a cnvrg deployment. Hooks are triggered on a regular basis using argocd (whenever we sync). 

The [following](https://github.com/AccessibleAI/cnvrgio-operator/blob/develop/chart/templates/install-hook-job.yml) hook runs after syncing and deletes the cnvrg namespace:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install
  namespace: default
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: cnvrg-bootstrap
      containers:
        - name: cnvrgapp
          image: {{.Values.hookImage}}
          args:
            - /bin/bash
            - -c
            - |
              kubectl delete namespace cnvrg --ignore-not-found
              while (( $(kubectl get namespace | grep cnvrg | wc -l ) != 0 )); do
                echo "waiting for ns will be deleted. . . ";
                sleep 1
              done
              kubectl create namespace cnvrg
      restartPolicy: Never
```

Deleting the namespace is likely to cause downtime and most importantly data loss as PVCs are also deleted. 

This may be an issue caused by using ArgoCD and not helm directly; however, the operator and the `cnvrg-app` CRD don't seem to be sharing many attributes and from the looks of it could be separate into sub charts. 

## Potential solutions

1. separate the charts entirely
2. In the chart provide the ability to toggle operator deployment / cnvrg-app deployment. This would allow us to deploy the chart twice with two different parameter sets (one for operator, one for crd).
3. Rework the helm jobs to not delete crucial resources like the namespace. The user would then be responsible for fully removing a cnvrg deployment themselves before redeploying.
