### ISSUE TITLE
Istio installed even when it is disabled

### ISSUE THREAD

**Issue by Addyvan** [AccessibleAI/cnvrgio-operator#76]
operator versions: `2.14.0`, `2.15.0-rc1`

Snippet from the cnvrgapp:
```yaml
networking:
    enabled: "true"
    https:
      cert: tls.crt
      certSecret: cnvrg-cert
      enabled: "false"
      key: tls.key
    ingress:
      enabled: "true"
      perTryTimeout: 10s
      retriesAttempts: "10"
      timeout: 100s
    ingressType: istio
    istio:
      enabled: "false"
      externalIp: ""
      gwName: cnvrg-gateway
      hub: docker.io/istio
      ingressSvcAnnotations: ""
      loadBalancerSourceRanges: ""
      mixerImage: mixer
      operatorImage: docker.io/istio/operator:1.8.1
      pilotImage: pilot
      proxyImage: proxyv2
      tag: 1.8.1
```

Given these parameters, istio shouldn't be installed but it the operator is still creating it upon installing:
```
$ k get pods -n cnvrg 
NAME                                           READY   STATUS     RESTARTS   AGE
app-86d4ffbdc4-s7flm                           0/1     Init:0/4   0          3m54s
cnvrg-operator-6bb95db9ff-gh9ml                1/1     Running    0          5m28s
elastalert-85495589fc-dg62p                    0/1     Pending    0          4m1s
elasticsearch-0                                0/1     Pending    0          4m1s
hyper-5f6495f568-4zhgx                         1/1     Running    0          3m53s
istio-ingressgateway-5f6bbbc76f-6gsph          1/1     Running    0          4m15s
istio-operator-7b5ffc7489-s6ghx                1/1     Running    0          4m56s
istiod-7fbb45cfc-fk29f                         1/1     Running    0          4m26s
kibana-57c7774bc8-xvkzx                        1/1     Running    0          4m
minio-d79579c7c-tldtf                          0/1     Pending    0          4m7s
minio-exporter-token-r87b7                     0/1     Init:0/1   0          3m56s
mpi-operator-5b8d56788d-hz4qn                  1/1     Running    0          3m49s
postgres-b5489f8d6-l69hg                       0/1     Pending    0          4m11s
redis-9656567f7-t8vb6                          0/1     Pending    0          4m4s
searchkiq-f7f65d68f-mj5mh                      0/1     Init:0/1   0          3m53s
sidekiq-7566c48b96-96j94                       0/1     Init:0/1   0          3m53s
sidekiq-7566c48b96-md5cp                       0/1     Init:0/1   0          3m53s
sidekiq-prometheus-exporter-59559f8f59-czwp5   1/1     Running    0          3m56s
systemkiq-575f694f64-dtc89                     0/1     Init:0/1   0          3m53s

```
